### PR TITLE
#2 + EIP100: Change difficulty adjustment to target mean block time including uncles

### PR DESCRIPTION
**Pull request by meowsbits**
Related to original question by @chunfu-yang in comment [here](https://github.com/etclabscore/ECLIPs/pull/2#issuecomment-472540475).

### CODE REVIEW

**Comment by meowsbits** [comment]
For further reference, it may be of interest to review the related https://github.com/ethereumproject/go-ethereum/pull/334.

**Review by zmitton — COMMENTED** [review]
looks useful especially since the ETC ethos is supposed to have a "capped total supply". 

Come to think of it though... how is that 210,000,000 cap implemented? This seems like it could directly affect the same code.

Looking at [ECIP 1017](https://github.com/ethereumproject/ECIPs/blob/master/ECIPs/ECIP-1017.md) it looks like they claim to have possibly accomplished something similar to EIP 100, but maybe in a different way?

> In the current ETC reward schedule, the total reward for uncles is higher than the reward received by the miner who also includes uncles. In this state, a miner is significantly diluting the value of his reward by including these uncled blocks. By equalizing the rewards to uncle block miners with the rewards to miners who include an uncle block, the reward structure is more fairly distributed. In addition, equalizing the uncle rewards reduces the incentive for miners to set up an ETC “uncle farm,” and instead drives them to better secure the network by competing for the latest “real block.”

@meowsbits is ECIP 1017 already merged into multi-geth, and might it already solve this?

**Review by soc1c — APPROVED** [review]
:+1: EIP-100 should be part of this spec.

**Comment by meowsbits** [comment]
@zmitton the ECIP1017 monetary policy is indeed included in multi geth now (it's necessary for ETC support); however that only describes the reward rates for block production, and doesn't deal directly with difficulty at all.

w/r/t the cap; the disinflation schedule reduces block miner reward (and similary uncle reward) by 20% every 5 million blocks.

**Comment by zmitton** [comment]
ok, here was my thought: the point of EIP100 is because currently when uncles get added, it makes the total block reward (inflation) greater. And it currently will not cause the block time to decrease of the difficulty to increase, so it effectively allows a bug where miners can increase the inflation.

This is why I thought we could have the bug, and the 210M cap may not be as "ridged" as we had thought.

So this would be _pro_ argument. 

Then looking at EIP 1017 it said something about fixing uncle rewards that I did not quite understand. 

Sounds like you are aware of how EIP 1017 works so looks good to me 👍

**Comment by meowsbits** [comment]
Closing via #10, where this proposal has been included.

**Pull request closed without merging**
